<?php
// $Id$

/**
 * hook_help() implementation
 */
function site_map_help($section = 'admin/help#site_map') {
  $output = '';

  switch ($section) {

    case 'admin/modules#description':  // Displayed in admin/system/modules where modules are enabled/disabled
      $output = t('Display a site map.');
      break;
    case 'sitemap':
      $output = variable_get('site_map_message', '');
      break;

  }

  return $output;
}

/**
 * hook_perm() implementation
 */
function site_map_perm() {
  return array("access site map", "administer site map");
}

/**
 * hook_settings() implementation
 */
function site_map_settings() {
  $output .= form_textarea(t('Site map message'), 'site_map_message', variable_get('site_map_message', ''), 60, 10, t('Define a message to be displayed above the site map.'));
  $output .= form_checkbox(t('Show node counts by categories'), 'site_map_show_count', 1, variable_get('site_map_show_count', 1), t('When enabled, this option will show the number of nodes in each taxonomy term.'));
  $output .= form_checkbox(t('Include navigation menus'), 'site_map_show_nav_menus', 1, variable_get('site_map_show_nav_menus', 1), t('When enabled, this option will include the fully-expanded top-level navigation menus in the site map'));
  $output .= form_checkbox(t('Include RSS links by categories'), 'site_map_show_rss_links', 1, variable_get('site_map_show_rss_links', 1), t('When enabled, this option will show links to the RSS feeds for each category.'));
  $output .= form_textfield(t('RSS feed depth'), 'site_map_rss_depth', variable_get('site_map_rss_depth', 'all'), 3, 10, t('Specify how many subcategories should be included in the RSS feed.  Enter "all" to include all subcategories or "0" to include no subcategories.'));

  return $output;
}

/**
 * hook_menu() implementation
 */
function site_map_menu() {
   $items[] = array(
     'path' => 'sitemap',
     'title' => t('site map'),
     'callback' => '_site_map_page',
     'access' => (user_access('access site map') || user_access('administer site map'))
    );

  return $items;
}

/**
 * The site map
 */
function _site_map_page() {
  //
  // Vocabulary and menu trees are compiled and passed to theme functions
  // individually.
  //

  if (variable_get('site_map_show_nav_menus', 1)) {
    //
    // Compile the menu trees.
    // All the defined items in the 'Navigation' tree will be rendered. The items
    // must be visible, of course.
    //
    $output .= theme('site_map_menu_tree', 1);
  }

  //
  // Compile the vocabulary trees.
  //
  $result = db_query('SELECT vid,name,description FROM {vocabulary}');
  while ($t = db_fetch_object($result)) {
    $tree = taxonomy_get_tree($t->vid);

    $output .= theme('site_map_taxonomy_tree', $tree, variable_get('site_map_show_count', 1), $t->name, $t->description);
  }

  print theme('page', $output);
}

/**
 * Themeable site map trees, called by _site_map_page(), to render a menu tree.
 *
 * @param $menu The item from menu_get_menu() that should be rendered.
 * @return A string representing a rendered tree.
 */
function theme_site_map_menu_tree($item = 1) {
  $menu = menu_get_menu();

  foreach ($menu['visible'][$item]['children'] as $child) {
    $output .= theme('site_map_menu_item', $child);
  }

  if ($output) {
    $output = '<div class="tree"><ul>'."\n$output\n</ul></div>\n";

    if ($menu['visible'][$item]['title']) {
      $output = '<div class="name">'.$menu['visible'][$item]['title']."</div>\n".$output;
    }

    $output = '<div class="site_map">'.$output."</div>\n";
  }

  return $output;
}

/**
 * Themeable site map trees, called by _site_map_page(), to render menu items.
 *
 * @param $menu The item from menu_get_menu() that should be rendered.
 * @return A string representing a rendered tree.
 */
function theme_site_map_menu_item($item) {
  $menu = menu_get_menu();

  $output = '<li>';
  $output .= l($menu['visible'][$item]['title'], $menu['visible'][$item]['path']);

  if ($menu['visible'][$item]['children']) {
    $output .= '<ul>';
    foreach ($menu['visible'][$item]['children'] as $child) {
      $output .= theme('site_map_menu_item', $child);
    }
    $output .= "</ul>\n";
  }

  $output .= "</li>\n";

  return $output;
}

/**
 * Themeable site map trees, called by _site_map_page(), to render taxonomy trees.
 *
 * @param $tree The results of taxonomy_get_tree() with optional 'count' fields.
 * @param $show_count Enabled node count if set.
 * @param $name An optional name for the tree. (Default: NULL)
 * @param $description An optional description of the tree. (Default: NULL)
 * @return A string representing a rendered tree.
 */
function theme_site_map_taxonomy_tree(&$tree, $show_count, $name = NULL, $description = NULL) {
  $name && $output = '<div class="name">'.$name.'</div>';
  $description && $output .= '<div class="description">'.$description.'</div>';

  $show_rss_links = variable_get('site_map_show_rss_links', 1);
  if ($show_rss_links) {
    $rss_depth = variable_get('site_map_rss_depth', 'all');
    if (!is_numeric($rss_depth) || $rss_depth < 0) {
      $rss_depth = 'all';
    }
  }

  $last_depth = -1;
  $output .= '<div class="tree">';
  foreach ($tree as $term) {
    //
    // Adjust the depth of the <ul> based on the change
    // in $term->depth since the $last_depth.
    //
    if ($term->depth > $last_depth) {
      for ($i = 0; $i < ($term->depth - $last_depth); $i++) {
        $output .= '<ul>';
      }
    }
    else if ($term->depth < $last_depth) {
      for ($i = 0; $i < ($last_depth - $term->depth); $i++) {
        $output .= '</ul>';
      }
    }

    //
    // Display the $term.  If $term->count exists, show the count too.
    //
    $output .= '<li>';
    $output .= l(check_output($term->name), 'taxonomy/term/'. $term->tid, array('title' => $term->description));
    if ($show_rss_links) {
      $output = $output . ' (' . l(t('RSS'), "taxonomy/term/{$term->tid}/{$rss_depth}/feed") . ')';
    }
    
    if ($show_count) {
      $count = taxonomy_term_count_nodes($term->tid);
      $output .= " ($count)\n";
    }

    $output .= "</li>\n";

    //
    // Reset $last_depth in preparation for the next $term.
    //
    $last_depth = $term->depth;
  }

  //
  // Bring the depth back to where it began, -1.
  //
  if ($last_depth > -1) {
    for ($i = 0; $i < ($last_depth + 1); $i++) {
      $output .= '</ul>';
    }
  }

  $output .= "</div>\n";

  return '<div class="site_map">'.$output.'</div>';
}

?>
